Style/Documentation:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Metrics/CyclomaticComplexity:
  Max: 25


Metrics/PerceivedComplexity:
  Max: 25


Naming/MethodParameterName:
  AllowedNames:
   - x
   - y
